import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ClientOnly from "@/components/ClientOnly";
import ToasterProvider from "@/providers/ToastProvider";
import VideoModal from "@/components/Modal/VideoModal";
import NotSignInModal from "@/components/Modal/NotSignInModal";

const inter = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} overflow-hidden`}>
          <ClientOnly>
            <ToasterProvider />
            <VideoModal />
            <NotSignInModal/>
          </ClientOnly>
          <div>{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
